version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: